#  Introduction
NumPy is the foundation of the Python machine learning stack. NumPy allows for
efficient operations on the data structures often used in machine learning: vectors,
matrices, and tensors. While NumPy is not the focus of this book, it will show up fre‐
quently throughout the following chapters. This chapter covers the most common
NumPy operations we are likely to run into while working on machine learning
workflows

## 1.1 Creating Vector

In [1]:
import numpy as np

In [2]:
# Creating Vector as a Row and Column
vector_row =np.array([1,2,3])
vector_col=np.array([[1],[2],[3]])

In [3]:
vector_row

array([1, 2, 3])

In [4]:
vector_col

array([[1],
       [2],
       [3]])

## 1.2  Creating Matrix

In [6]:
matrix=np.array([[1,2],[1,2],[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

## 1.3 Creating Sparse Matrix

In [7]:
from scipy import sparse 

In [9]:
matrix=np.array([[0,0],[0,1],[3,0]])
matrix_sparse=sparse.csr_matrix(matrix)

In [11]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


## 1.4 Selecting Elements

In [13]:
vector =np.array([1,2,3,4,5,6])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                [7, 8, 9]])


In [14]:
# Select third element of vector
vector[2]

3

In [15]:
# Select third element of Matrix[]
matrix[1,1]

5

### Note :
Like most things in Python, NumPy arrays are zero-indexed, meaning that the index
of the first element is 0, not 1. With that caveat, NumPy offers a wide variety of meth‐
ods for selecting (i.e., indexing and slicing) elements or groups of elements in arrays:

In [16]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [17]:
# Select everything up to and including the third element
vector[:3]


array([1, 2, 3])

In [18]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [19]:
# Select the last element
vector[-1]

6

In [21]:
matrix[:2,:]


array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
matrix[:,:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [27]:
matrix[:,-1:]

array([[3],
       [6],
       [9]])

In [32]:
#Select all rows and the second column
matrix[:,1:2]


array([[2],
       [5],
       [8]])

## 1.5 Describing a Matrix

In [33]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [34]:
# View number of rows and columns
matrix.shape

(3, 4)

In [35]:
matrix.size

12

In [36]:
# View number of dimensions
matrix.ndim

2

## 1.6 Applying Operations to Elements

In [37]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [38]:
# Create function that adds 100 to something
add_100 = lambda i: i + 100

In [39]:
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [40]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)


array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

### Note :
NumPy’s vectorize class converts a function into a function that can apply to all ele‐
ments in an array or slice of an array. It’s worth noting that vectorize is essentially a
for loop over the elements and does not increase performance. Furthermore, NumPy
arrays allow us to perform operations between arrays even if their dimensions are not
the same (a process called broadcasting). For example, we can create a much simpler
version of our solution using broadcasting:

In [41]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

## 1.7 Finding the Maximum and Minimum Values

In [42]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [43]:
# Return maximum element
np.max(matrix)

12

In [44]:
# Return minimum element
np.min(matrix)

1

### Note:
Often we want to know the maximum and minimum value in an array or subset of an
array. This can be accomplished with the max and min methods. Using the axis
parameter we can also apply the operation along a certain axis:

In [45]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([ 9, 10, 11, 12])

In [46]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([ 4,  8, 12])

## 1.8 Calculating the Average, Variance, and Standard Deviation

In [47]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [48]:
# Return mean
np.mean(matrix)

6.5

In [51]:
np.var(matrix)


11.916666666666666

In [54]:
# Return standard deviation
np.std(matrix)

3.452052529534663

### Note :
Just like with max and min, we can easily get descriptive statistics about the whole
matrix or do calculations along a single axis:

In [55]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([5., 6., 7., 8.])

## 1.9 Reshaping Arrays

In [56]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [57]:
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## 1.10 Transposing a Vector or Matrix

In [58]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [59]:
# Transpose matrix
matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 1.11 Flattening a Matrix


In [60]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [61]:
# Flatten matrix
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.12 Finding the Rank of a Matrix

In [62]:
# Create matrix
matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                  [1, 1, 15]])

np.linalg.matrix_rank(matrix)

2

## 1.13 Calculating the Determinant

In [63]:
# Create matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

0.0

## 1.14 Getting the Diagonal of a Matrix

In [64]:
# Create matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

In [66]:
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

## 1.15 Calculating the Trace of a Matrix

In [67]:
# Create matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

In [68]:
# Return trace
matrix.trace()


14

## 1.16 Finding Eigenvalues and Eigenvectors

In [69]:
# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])


In [70]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [71]:
# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [72]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 1.17 Calculating Dot Products

In [73]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [74]:
# Calculate dot product
np.dot(vector_a, vector_b)

32

##  1.18 Adding and Subtracting Matrices

In [76]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 2]])

In [77]:
# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])


In [78]:
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [80]:
np.subtract(matrix_a, matrix_b)


array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [81]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.19 Multiplying Matrices

In [83]:
# Create matrix
matrix_a = np.array([[1, 1],
                      [1, 2]])

In [84]:
# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

In [85]:
# Multiply two matrices
np.dot(matrix_a, matrix_b)


array([[2, 5],
       [3, 7]])

## 1.20 Inverting a Matrix

In [86]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

In [87]:
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

## 1.21 Generating Random Values

In [89]:
# Set seed
np.random.seed(0)

In [91]:
# Generate three random floats between 0.0 and 1.0

np.random.random(3)

array([0.54488318, 0.4236548 , 0.64589411])